/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.html"],
  prefix: "tw-",
  theme: {
    extend: {
      colors: {
        "moderate-orange": "#b88e2f",
        main: "var(--main-clr)",
        dark: {
          33: "#333333",
          66: "#666666",
        },
      },
      spacing: {
        18: "4.5rem",
        19: "4.75rem",
        25: "6.25rem",
        250: "62.5rem",
      },
      fontFamily: {
        // montserrat: "var(--main-font)",
        poppins: "var(--secondary-font)",
      },
      transitionDuration: {
        DEFAULT: "200ms",
      },
      animation: {
        rotate: "spin 17s linear infinite",
        // loader: "spin 1000ms cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "rotate-rev": "spin 17s linear infinite alternate-reverse",
        "pulse-slow": "pulse 6s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        bounce: {
          "0%, 100%": {
            transform: "translateY(-100%)",
            animationTimingFunction: "cubic-bezier(0.8,0,1,1)",
          },
          "50%": {
            transform: "none",
            animationTimingFunction: "cubic-bezier(0,0,0.2,1)",
          },
        },
      },
    },
  },
  plugins: [
    ({ addComponents, addVariant }) => {
      addComponents({
        html: {
          "@media (max-width: 1280px)": { fontSize: "14px" },
          "@media (max-width: 640px)": { fontSize: "10px" },
          "@media (max-width: 400px)": { fontSize: "9px" },
        },
        body: {
          fontFamily: "var(--main-font)",
          color: "#333",
        },
        img: {
          userSelect: "none",
          WebkitUserDrag: "none",
        },
        ".container": {
          marginRight: "auto",
          marginLeft: "auto",
        },
        ".nav-link": {
          color: "#333",
          fontSize: "1rem",
          lineHeight: "1.5rem",
          fontWeight: "500",
          fontFamily: "var(--secondary-font)",
          transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
          borderColor: "var(--main-clr)",
          "&:hover, &.active": {
            color: "var(--main-clr)",
            borderBottomWidth: ".125rem",
          },
          "&.active": {
            fontWeight: "600",
          },
        },
        ".menu-btn": {
          border: "none",
          outline: "none",
          background: "transparent",
          padding: "0",
          display: "flex",
          alignItems: "flex-end",
          width: "2.5rem",
          flexDirection: "column",
          gap: ".4rem",
          transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
          span: {
            backgroundColor: "#333",
            display: "inline-block",
            height: ".25rem",
            transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
            "&:nth-child(1)": { width: "100%" },
            "&:nth-child(2)": { width: "75%" },
            "&:nth-child(3)": { width: "50%" },
          },
          "&:is([aria-expanded='true'])": {
            span: {
              "&:nth-child(1)": {
                transform: "rotate(45deg) translate(20%, 180%)",
              },
              "&:nth-child(2)": {
                opacity: "0",
                width: "100%",
              },
              "&:nth-child(3)": {
                transform: "rotate(-45deg) translate(20%, -180%)",
                width: "100%",
              },
            },
          },
        },
        ".dark-btn, .dark-btn-outline": {
          display: "inline-block",
          padding: ".5rem .5rem",
          borderRadius: ".75rem",
          fontSize: "1rem",
          fontWeight: "600",
          width: "100%",
          textAlign: "center",
          position: "relative",
          textWrap: "nowrap",
          transition: "all 500ms cubic-bezier(0.4, 0, 0.2, 1)",
          border: "1px solid #000",
          "&::after": {
            content: '""',
            position: "absolute",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            backgroundColor: "#ffffff80",
            borderRight: "2px solid #fff",
            transform: "translate(-105%, 0)",
            opacity: "0.8",
            transition: "all 500ms cubic-bezier(0.4, 0, 0.2, 1)",
            zIndex: "-10",
          },

          "&:hover": {
            "&::after": {
              transform: "translate(0, 0)",
              opacity: "0",
              zIndex: "10",
            },
          },
        },
        ".dark-btn": {
          color: "#fff",
          backgroundColor: "#000",
        },
        ".dark-btn-outline": {
          color: "#000",
          background: "transparent",
          "&:hover": {
            backgroundColor: "#000",
            color: "#fff",
          },
        },
        ".carousel-cont": {
          display: "grid",
          gridAutoFlow: "column",
          gridAutoColumns: "calc(100% / 6 - 1.5rem)",
          gap: "1.5rem",
          overflowX: "auto",
          scrollbarWidth: "none",
          scrollSnapType: "x mandatory",
          scrollBehavior: "smooth",
          ".carousel-card": {
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: "1rem",
            a: {
              "-webkit-user-drag": "none",
              transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
              "&:hover": {
                color: "var(--main-clr)",
              },
            },
            img: {
              borderRadius: "1rem",
            },
            ".txt": {
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              fontSize: "1rem",
              lineHeight: "1.5rem",
              fontWeight: "700",
              color: "var(--dark-33)",
              width: "100%",
              textWrap: "wrap",
            },
          },
        },
        ".preloader": {
          position: "fixed",
          top: "0",
          left: "0",
          width: "100%",
          height: "100%",
          zIndex: "999999999",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#fff",
          span: {
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            width: "8rem",
            height: "8rem",
            background: "transparent",
            borderRadius: "50%",
            borderLeft: ".75rem solid var(--main-clr)",
            animation: "spin 1500ms cubic-bezier(0.4, 0, 0.6, 1) infinite",
          },
        },
        ".preloader-2": {
          position: "fixed",
          top: "0",
          left: "0",
          width: "100%",
          height: "100%",
          zIndex: "999999999",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#fff",
          div: {
            width: "6rem",
            height: "8rem",
            display: "flex",
            alignItems: "flex-end",
            justifyContent: "center",
            borderBottom: "2px solid var(--main-clr)",
            // boxShadow: "0 0 .5rem 0 #0008",
            span: {
              display: "inline-block",
              width: "2rem",
              height: "2rem",
              borderRadius: "50%",
              backgroundColor: "var(--main-clr)",
              animation: "tw-bounce 1s infinite",
            },
          },
        },
        ".products-cont": {
          display: "grid",
          gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
          gap: "2rem",
          "@media (min-width: 640px)": {
            gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
          },
          "@media (min-width: 768px)": {
            gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
          },
          "@media (min-width: 1024px)": {
            gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
          },
        },
        ".product-cart": {
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          position: "relative",
          backgroundColor: "#F4F5F7",
          overflow: "hidden",
          "&.label::before, &.label-new::before": {
            color: "#fff",
            fontSize: "1rem",
            fontWeight: "500",
            fontFamily: "var(--secondary-font)",
            width: "3rem",
            height: "3rem",
            borderRadius: "50%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            position: "absolute",
            top: "4%",
            right: "5%",
          },
          "&.label::before": {
            content: "attr(data-label)",
            backgroundColor: "#e97171",
          },
          "&.label-new::before": {
            content: "'New'",
            backgroundColor: "#2EC1AC",
          },
          "> img": {
            width: "100%",
          },
          ".cart-body": {
            display: "flex",
            flexDirection: "column",
            alignItems: "start",
            gap: ".5rem",
            padding: "1rem 1.25rem 2rem 1rem",
            fontFamily: "var(--secondary-font)",
            ".name": {
              fontSize: "1.5rem",
              lineHeight: "2rem",
              fontWeight: "600",
              color: "#3a3a3a",
            },
            ".desc": {
              fontSize: "1rem",
              lineHeight: "1.5rem",
              fontWeight: "500",
              color: "#898989",
            },
            ".price-cont": {
              display: "flex",
              alignItems: "center",
              gap: "1rem",
              textWrap: "nowrap",
              ".cur": {
                fontSize: "1.25rem",
                lineHeight: "1.75rem",
                fontWeight: "600",
                color: "#3a3a3a",
              },
              ".prev": {
                fontSize: "1rem",
                lineHeight: "1.5rem",
                color: "#b0b0b0",
                textDecoration: "line-through",
              },
            },
          },
          ".show-on-hover": {
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            gap: "1.5rem",
            position: "absolute",
            inset: "0",
            width: "100%",
            height: "100%",
            fontFamily: "var(--secondary-font)",
            fontWeight: "600",
            zIndex: "10",
            transition: "all 300ms cubic-bezier(0.4, 0, 0.2, 1)",
            backgroundColor: "#3a3a3a00",
            opacity: "0",
            ".cart-btn": {
              fontSize: "1rem",
              lineHeight: "1.5rem",
              fontWeight: "600",
              textAlign: "center",
              padding: "0.75rem 3.5rem",
              color: "var(--main-clr)",
              backgroundColor: "#fff",
              borderRadius: ".25rem",
              border: "none",
              transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
              "&:hover": {
                backgroundColor: "var(--main-clr)",
                color: "#fff",
                borderRadius: "1rem",
              },
            },
            ".row-btns": {
              display: "flex",
              alignItems: "center",
              gap: ".75rem",
              button: {
                fontSize: "1rem",
                lineHeight: "1.5rem",
                fontWeight: "600",
                color: "#fff",
                textTransform: "capitalize",
                borderRadius: "0.375rem",
                padding: "0.25rem",
                transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
                "&:hover": {
                  backgroundColor: "#3a3a3a",
                  color: "#fff",
                },
                img: {
                  display: "inline-block",
                  width: "1rem",
                  height: "1rem",
                },
              },
            },
          },
          "&:hover": {
            ".show-on-hover": {
              backgroundColor: "#3a3a3ab8",
              opacity: "1",
            },
          },
        },
      });
      addVariant("path", "& path");
      addVariant("focus", "&:focus");
      addVariant("focus-visible", "&:focus-visible");
      addVariant("active", "&.active");
      addVariant("child-hover-effect", "&:hover > *");
    },
  ],
  corePlugins: {
    textOpacity: false,
    ringOpacity: false,
    borderOpacity: false,
    divideOpacity: false,
    backdropOpacity: false,
    backgroundOpacity: false,
    placeholderOpacity: false,
  },
};
